# Generated by Django 5.0.2 on 2024-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'EMPLOYEE'), (2, 'EMPLOYER')]),
        ),
    ]
