# Generated by Django 5.0.2 on 2024-03-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'EMPLOYEE'), ('EMPLOYER', 'EMPLOYER')], max_length=100),
        ),
    ]
