# Generated by Django 5.0.2 on 2024-03-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
