# Generated by Django 5.0.2 on 2024-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userprofile_username_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('EMPLOYER', 'Employer')], default='EMPLOYEE', max_length=100),
        ),
    ]
