# Generated by Django 5.0.3 on 2024-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprofile_avatar_userprofile_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
