# Generated by Django 5.0.2 on 2024-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processHandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('reqId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField(null=True)),
                ('jdText', models.TextField()),
                ('jdTitle', models.TextField()),
                ('uploadedDateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('profileId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.BigIntegerField(null=True)),
                ('resumeText', models.TextField()),
                ('fileName', models.TextField()),
                ('uploadedDateTime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='jdText',
        ),
        migrations.RemoveField(
            model_name='process',
            name='resumeText',
        ),
        migrations.AddField(
            model_name='process',
            name='profileId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='reqId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='userId',
            field=models.BigIntegerField(null=True),
        ),
    ]
