# Generated by Django 5.0.2 on 2024-04-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processHandler', '0002_jobdescription_resume_remove_process_jdtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profileTitle',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='jdTitle',
            field=models.TextField(null=True, unique=True),
        ),
    ]
