# Generated by Django 5.0.2 on 2024-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processHandler', '0004_alter_resume_profiletitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
