# Generated by Django 5.0.2 on 2024-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processHandler', '0005_resume_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='reqId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profileId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
