# Generated by Django 5.0.2 on 2024-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processHandler', '0006_alter_jobdescription_reqid_alter_process_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='reqId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profileId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
