# Generated by Django 5.0 on 2023-12-26 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdecription',
            name='uploadedDateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 22, 5, 14, 712480)),
        ),
    ]
