# Generated by Django 5.0.2 on 2024-02-11 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('resumeKeyWords', models.TextField(null=True)),
                ('jdKeyWords', models.TextField(null=True)),
                ('uploadedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'dataextraction_keywords',
            },
        ),
    ]
