# Generated by Django 5.0 on 2024-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_id_alter_resume_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
