# Generated by Django 5.0 on 2024-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_id_alter_candidate_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='fullName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='githubUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='linkedinUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phoneNumber',
            field=models.TextField(null=True),
        ),
    ]
