# Generated by Django 5.0 on 2024-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_id_alter_experience_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
