# Generated by Django 5.0 on 2024-01-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataExtractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resumeId',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resumeId',
        ),
        migrations.DeleteModel(
            name='JobDecription',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resumeId',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
