# Generated by Django 5.0.2 on 2024-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataExtractor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='skillsAbsent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='skillsPresent',
            field=models.TextField(null=True),
        ),
    ]
