# Generated by Django 5.0.1 on 2024-02-02 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('experience_score', models.FloatField(null=True)),
                ('education_score', models.FloatField(null=True)),
                ('final_score', models.FloatField(null=True)),
                ('uploadedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'score',
            },
        ),
    ]
