# Generated by Django 5.0.2 on 2024-04-25 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportExtractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultScoreConfig',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('keywordsConfig', models.IntegerField(null=True)),
                ('experienceConfig', models.IntegerField(null=True)),
                ('educationConfig', models.IntegerField(null=True)),
                ('uploadedDateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'default_score_config',
            },
        ),
        migrations.RenameField(
            model_name='scoreconfig',
            old_name='id',
            new_name='jobId',
        ),
    ]
