# Generated by Django 5.0 on 2024-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobDescription', '0002_alter_jobdescription_id_alter_jobdescription_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='uploadedDateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
