# Generated by Django 5.0 on 2023-12-26 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeText', models.TextField()),
                ('uploadedDateTime', models.DateTimeField(default=datetime.datetime(2023, 12, 26, 9, 49, 7, 9329))),
            ],
        ),
    ]
